language: cpp
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libgmp-dev
    - libmpfr-dev
    - libmpc-dev
    - binutils-dev
    - g++-4.7

env:
  global:
    - secure: "b+fS4EkSfk+z+6Gk114TmbEA4O3okYq2GgK7sRc2B1zxx0wjCLKQqtwZRawlGbDocO94zpaCEVugMChAd4hqsEQio02YKSvQH2RWq03FYl4Uqs287p/UDW5sZzhwM0D5fhWgdncNfVExdRbbdAFbGjHlZIYnEgr8bcHU7WsbnBbpESsB3dslFFjLG9VzX2Bm1jcDNpZTHzveU1XxMecIJ1JQjBhJoXmZiySgancqkQeGitOqq/e0yKyc8clLCyynVRtgHfR5IPaBYqnG0j2jULtjj8xAjX7TZTU6oI7RJ6SD09tj+6LpmSq6EDEdkIaDuT6r++Yx6yCBuEl6h+n94dIcRPMAIyNW7FtW4/AtCk4JCkC1RlB+omcpDg2uZL9lwMRaYsBvY6eaIAIdCwWU7VC+ixBaOCxllIDjQTby9iO++EOHNzX6A8mUaYVT8Vh5vkRzAhc6VTJgk0TfzaViwRYvib7qD4dIovKp4byhHS/fGImN3jGU3ZQO9fb6S/DdPeXj+PlCdme3yK+0M+faLsb8tBeJHZaQqiyB2onZOJ5cSl/sqSU+DXXCtN30uj+Vpceedv71NZx2cKYw4c64dzbdNlYd/RDk1JyaKK1drtyMXcPsEV26egbsM+jrzVR9NjdlX6eqB6GISrlgOkGkaYfdBJH/9Pzv5oRmoIER2b8="

  ## All these variables are sent into the bin/test_travis.sh script. See this
  ## script to know how they are used. Most of them are just passed to cmake,
  ## so if they are not set, cmake will use a default value. For the rest, the
  ## bin/test_travis.sh script usually checks for either "yes" or "no" in an if
  ## statement, so if the variable is not set, the other if branch will get
  ## executed.
  matrix:
  ## Out of tree builds (default):
  - BUILD_TYPE="Debug" WITH_BFD="yes" PYTHON_VERSION="2.7" TRIGGER_FEEDSTOCK="yes"

  ## In-tree builds (we just check a few configurations to make sure they work):
  # Debug build with Python 2.7:
  - BUILD_TYPE="Debug" WITH_BFD="yes" PYTHON_VERSION="2.7"
  # Release build shared lib with Python 2.7:
  - PYTHON_VERSION="2.7" BUILD_SHARED_LIBS="yes"

  # These test the setup.py file
  - PYTHON_VERSION="2.6" WITH_MPFR="yes" INTEGER_CLASS="gmp"
  - PYTHON_VERSION="2.7" WITH_MPC="yes"
  - PYTHON_VERSION="3.3" WITH_MPC="yes"
  - PYTHON_VERSION="3.4" WITH_MPFR="yes" WITH_NUMPY="yes"
  - PYTHON_VERSION="3.5" WITH_MPFR="yes" WITH_NUMPY="yes"

matrix:
  exclude:
    - compiler: clang
    - os: osx
  include:
    - env: BUILD_TYPE="Debug" WITH_BFD="yes" WITH_PIRANHA="yes" PYTHON_VERSION="2.7"
      compiler: gcc
      os: linux
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - boost-latest
          packages:
          - libgmp-dev
          - libmpfr-dev
          - binutils-dev
          - libboost-serialization1.55-dev
          - libboost-iostreams1.55-dev
          - g++-4.8
    - env: BUILD_TYPE="Debug" WITH_BFD="yes" PYTHON_VERSION="3.5"
      compiler: clang
      os: linux
    - env: BUILD_TYPE="Release" PYTHON_VERSION="2.7"
      compiler: clang
      os: linux
    - env: BUILD_TYPE="Debug" PYTHON_VERSION="2.7"
      compiler: clang
      os: osx
    - env: BUILD_TYPE="Release" PYTHON_VERSION="3.5"
      compiler: clang
      os: osx
    - env: BUILD_TYPE="Debug" PYTHON_VERSION="2.7" WITH_NUMPY="yes"
      compiler: gcc
      os: osx
    - env: BUILD_TYPE="Release" PYTHON_VERSION="3.5"
      compiler: gcc
      os: osx
    - env: BUILD_TYPE="Release" WITH_SAGE="yes" WITH_MPC="yes"
      compiler: gcc
      os: linux
      addons:
        apt:
          packages:
          - lrzip

install:
  - export PYTHON_SOURCE_DIR=`pwd`
  - export TEST_CPP="no"

  - git clone https://github.com/symengine/symengine symengine-cpp
  - cd symengine-cpp
  - export SOURCE_DIR=`pwd`
  - git checkout `cat ../symengine_version.txt`

  # Setup travis for C++ library
  - if [[ "${WITH_SAGE}" != "yes" ]]; then source bin/install_travis.sh; fi

  # Setup travis for Python wrappers
  - cd $PYTHON_SOURCE_DIR
  - source bin/install_travis.sh

  # Build C++ library
  - cd symengine-cpp
  - bin/test_travis.sh

script:
  # Build Python wrappers and test
  - cd $PYTHON_SOURCE_DIR
  - bin/test_travis.sh

notifications:
  email: false
