language: cpp
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - binutils-dev
    - g++-4.7

env:
  global:
    - secure: "gdcw4nEd06q+E8yZkaqtgexX4kHgKqFuTRHKyx5QJBW/q+vL94ntbFft7jZssXEmFtijyjjNbhTucwcSaXIAP1X4tct5kHcuBH5LVvCxi7r4NfhERJDE/EAOS4xbQJ9IUHjdBWCWTCCiXpg0bG/1YcCVsppcKi2Z864CBDpa8DPuDUtyxFpkHW7PdALitLWDIIkIJU817JqYlJKcnR62OYGdVlHiUHhSGI6JKnqou7gf6fgXLsXNnUDUeWS+9vElOTV6OU7vHbG1Ka2N2vwpLIoBoSrw80EDAyP+QqqBRP1B2CyPGvEu9lTyqxUVkb0DAjsltn1bt36UVIb+l55B1JWPSriI3xiVstXa9D2Xb1uth9h712c0cwXw9LJ7YsXEcwdAfCRF/Zywt9IdwCWlnRkiGD2fOHPBkjpXVAV+2xFSD8WLuV6hc3xZjFLvzRxiDZ1CYSY+Wh6IxOp7411GT3BgtH0kEXb5+cg55cjPxgWAWOsU1WkrrWMl9DngeiWNwGZQCU+UkPB1WaITtA6JbFdEZPinZFWtYPMj6ZdA+ARkmwQnG6Y6sg37Zq76n8mDjLb5ECLXq22uRLaATl8lRLOaNDStg9PSxtVGON65NeesPMRFRC7+2ySQ/8KqsZZubHk7SoSY8APP+5mqzBuMbt2bnBVLmf04TI7RnVPSZ6A="

  ## All these variables are sent into the bin/test_travis.sh script. See this
  ## script to know how they are used. Most of them are just passed to cmake,
  ## so if they are not set, cmake will use a default value. For the rest, the
  ## bin/test_travis.sh script usually checks for either "yes" or "no" in an if
  ## statement, so if the variable is not set, the other if branch will get
  ## executed.
  matrix:
  # Debug builds:
  - BUILD_TYPE="Debug" WITH_BFD="yes" PYTHON_VERSION="2.7" TRIGGER_FEEDSTOCK="yes"
  - BUILD_TYPE="Debug" WITH_BFD="yes" PYTHON_VERSION="3.6"

  # Release builds:
  - PYTHON_VERSION="2.7" BUILD_SHARED_LIBS="yes"
  - PYTHON_VERSION="2.7" WITH_MPFR="yes" INTEGER_CLASS="gmpxx"
  - PYTHON_VERSION="3.3" WITH_MPC="yes"
  - PYTHON_VERSION="3.4" WITH_MPFR="yes" WITH_NUMPY="yes"
  - PYTHON_VERSION="3.5" WITH_MPC="yes" WITH_NUMPY="yes"
  - PYTHON_VERSION="3.6" WITH_MPC="yes" WITH_NUMPY="yes"

matrix:
  exclude:
    - compiler: clang
    - os: osx
  include:
    - env: BUILD_TYPE="Debug" WITH_BFD="yes" WITH_PIRANHA="yes" PYTHON_VERSION="2.7"
      compiler: gcc
      os: linux
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - binutils-dev
          - g++-4.8
    - env: BUILD_TYPE="Debug" WITH_BFD="yes" PYTHON_VERSION="3.5" WITH_LLVM="yes"
      compiler: clang
      os: linux
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - clang
          - libstdc++-4.8-dev
          - binutils-dev
    - env: BUILD_TYPE="Release" PYTHON_VERSION="2.7"
      compiler: clang
      os: linux
    - env: BUILD_TYPE="Debug" PYTHON_VERSION="2.7"
      compiler: clang
      os: osx
    - env: BUILD_TYPE="Release" PYTHON_VERSION="3.5"
      compiler: clang
      os: osx
    - env: BUILD_TYPE="Debug" PYTHON_VERSION="2.7" WITH_NUMPY="yes"
      compiler: gcc
      os: osx
    - env: BUILD_TYPE="Release" PYTHON_VERSION="3.5"
      compiler: gcc
      os: osx
    - env: BUILD_TYPE="Release" WITH_SAGE="yes" WITH_MPC="yes" PYTHON_VERSION="2.7"
      compiler: gcc
      os: linux

install:
  - export PYTHON_SOURCE_DIR=`pwd`
  - export TEST_CPP="no"
  - export MAKEFLAGS="-j2"

  - git clone https://github.com/symengine/symengine symengine-cpp
  - cd symengine-cpp
  - export SOURCE_DIR=`pwd`
  - git checkout `cat ../symengine_version.txt`
  - cd ..

  # Setup travis for C++ library
  - cd $SOURCE_DIR
  - source bin/install_travis.sh

  # Setup travis for Python wrappers
  - cd $PYTHON_SOURCE_DIR
  - source bin/install_travis.sh

  # Build C++ library
  - cd $SOURCE_DIR
  - bin/test_travis.sh
  - unset MAKEFLAGS

script:
  # Build Python wrappers and test
  - cd $PYTHON_SOURCE_DIR
  - bin/test_travis.sh

notifications:
  email: false

deploy:
  provider: pypi
  user: isuruf
  password:
    secure: "HsVXENZjVg05Mce5Ts6iG292Ch03YHETto/512Nu1R8xeRWeerMZpumBE2X0WPrDBuV/zLMlf/jc8rN6EX9GEGaBxTPwFq5tNRTFjShUcmSxWLWPVgF7fYm1+pPjkzODOTIHPkJB00nw22DUuF2kg/gCm7uZeaGNsBELNpKPJyRv9ShxOLqOxK+WR5QQw+xMmmq+ugsc1/kjnxuczcUs/dXyYfFrw9nrKD8qUPeyEsaea1jUxDIVLBtaxnwbmhtw+GPE5tH+5Q/Y8mA7epw5Znj47W+WxfF/sdtBt31m9KNmMcISYpvUHpcju/gTUAeRBU0Ln04teR6iMHUcQJerM0T61uZCNCoYQv1A9oVKA3NO1Gb6in8BqoR+wZB2po+g8U3x+nKGxJrFNekm9zAhs7yQEYnP6C9ekUpe+73qi6I6fzMB71sMJa6SegYL99z+UW6zjhIesf6nX43U+954pN7FsrIzkdTHW67YrBfKr8PEZ0VPxJzokWTPkYO5Qkvjp1TNyFBsV2DS5qpMMYHYxNDbxj5elYZxPt+bvRbtmMdS4p2ze5DVWEQbwW+jZydBoccH6uAhjXkFRil9/5LAJmwfIYcBrF6RkZu1VhSSIULhtOqtA7psSSBSprqyhPsvs8l13PUs92SogXCrYFfHgNR6J8UM3iiP0yooeV6Z+gw="
  on:
    condition: $TRIGGER_FEEDSTOCK = yes
    tags: true
